/* SPDX-License-Identifier: LGPL-3.0-or-later */

#pragma once

#define QUOTE_(x) #x
#define QUOTE(x) QUOTE_(x)

#define ROVER_MAJOR_VERSION 0
#define ROVER_MINOR_VERSION 2
#define ROVER_MICRO_VERSION 1
#define ROVER_BUILD_VERSION 0

#define ROVER_VERSION   ROVER_MAJOR_VERSION,ROVER_MINOR_VERSION,ROVER_MICRO_VERSION,ROVER_BUILD_VERSION
#define ROVER_VERSION_STR  QUOTE(ROVER_MAJOR_VERSION.ROVER_MINOR_VERSION.ROVER_MICRO_VERSION.ROVER_BUILD_VERSION)

#define ROVER_COMPANY      "A1ive"
#define ROVER_COPYRIGHT    "Copyright (c) 2026 A1ive"
#define ROVER_FILEDESC     "FsRover -- Filesystem browser"

#define ROVER_NAME         "Rover"
#define ROVER_PRODUCT      ROVER_NAME
#define ROVER_INTERNALNAME ROVER_NAME
#define ROVER_ORIGINALNAME ROVER_NAME ".exe"
